name: ContentfulMarketing
options:
  bundleIdPrefix: com.contentful
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  Contentful:
    url: https://github.com/contentful/contentful.swift
    from: 5.0.0
  RichTextRenderer:
    url: https://github.com/contentful/rich-text-renderer.swift
    from: 0.4.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: 7.0.0

targets:
  ContentfulMarketing:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: ContentfulMarketing/Sources/ContentfulMarketing
    info:
      path: ContentfulMarketing/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Contentful Marketing
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: 1
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              UISceneConfigurationName: Default Configuration
              UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: Contentful
        product: Contentful
      - package: RichTextRenderer
        product: ContentfulRichTextRenderer
      - package: Kingfisher
        product: Kingfisher
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.contentful.marketing
        PRODUCT_NAME: ContentfulMarketing
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"

